### PR TITLE
Test against Plone 5.1.

### PR DESCRIPTION
**Pull request by mbaechtold**

### CODE REVIEW

**Review by jone — APPROVED** [review]
Looks good 👍

**Comment by mbaechtold** [comment]
@jone, I don't think we need to cut a new release, since the changes only affect the testing. So I did not add an entry to the Changelog. What do you think?

**Comment by jone** [comment]
@mbaechtold I'd probably add a changelog entry and cut a release for marketing reasons 🤔

**Comment by mbaechtold** [comment]
@jone, should the new release be `1.1.0` or `2.0.0`? The current release is `1.0.1`.

**Comment by mbaechtold** [comment]
@jone, what do you think about the version numbering (see previous comment)?

**Comment by jone** [comment]
I'd go with `1.1.0`: we are just adding compatibility with the future 😉 
`2.0.0` would be apropriate for a rewrite.

**Pull request merged**
